version: '3.9'
services:
  # Next.jsの設定
  client:
    build:
      context: .
      dockerfile: /client/Dockerfile
    ports:
      - '3000:3000' # ホストの3000ポートをコンテナの3000ポートにバインド
    volumes:
      - ./client/src:/app # ソースコードをコンテナにマウント
    command: yarn dev

  # Laravelの設定
  api:
    build:
      context: ./api # Dockerfileの場所を指定
    volumes:
      - ./api/src:/var/www/html:Z # Laravelプロジェクトをコンテナにマウント
    ports:
      - '8080:80' # Apacheはデフォルトで80ポートを使用
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  # MySQLの設定
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

  # PHPMyAdminの設定
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '5000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:
